[package]
name = "Little_HyperService"
version = "0.1.0"
authors = ["Warren-Lamb <10warren10@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.12.31"
lazy_static = "1.3.0"
slab = "0.4.2"
futures = "0.1.28"
regex = "1.1.7"
